licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stats_utils",
    hdrs = ["stats_utils.h"],
    deps = [
        "//clusterers:clustering_stats_cc_proto",
        "@parcluster//parcluster/api:gbbs-graph",
        "@parcluster//parcluster/api:status_macros",
        "//external:gflags",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_protobuf//:protobuf",
        "@parcluster//parcluster/api:in-memory-clusterer-base",
    ],
)

cc_library(
    name = "stats_communities",
    hdrs = ["stats_communities.h"],
    deps = [
        "//clusterers:clustering_stats_cc_proto",
        "@parcluster//parcluster/api:gbbs-graph",
        "@parcluster//parcluster/api:status_macros",
        "//external:gflags",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_protobuf//:protobuf",
        "@parcluster//parcluster/api:in-memory-clusterer-base",
    ],
)

cc_library(
    name = "stats_correlation",
    hdrs = ["stats_correlation.h"],
    deps = [
        "//clusterers:clustering_stats_cc_proto",
        "@parcluster//parcluster/api:gbbs-graph",
        "@parcluster//parcluster/api:status_macros",
        "//external:gflags",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_protobuf//:protobuf",
        "@parcluster//parcluster/api:in-memory-clusterer-base",
    ],
)